.travis.yml, Dockerfile
=> [WIP] Travis-CI for CEPCSW

Utilities/DataHelper/CMakeLists.txt, Utilities/DataHelper/DataHelper/ClusterShapes.h, Utilities/DataHelper/src/ClusterShapes.cc
For WIP: Unify the MarlinUtil in CEPCSW #19
=> update ClusterShapes.cc to use new GSL Library

Examples/options/tut_detsim_SDT.py
This script is used to run simulation of SDT.
To visualize the detector, add env var `VIS=1`.
=> DONE: Add a script for SDT simulation.

docs/simulation-tutorial/index.html
* The source code is edited in the [Live Note](https://jupyter.ihep.ac.cn/p/9apEX7C3-)
=> Slides for CEPCSW tutorial

docs/quickstart.md
=> WIP: update the quickstart according to Xin's comment #38.

Simulation/DetSimDedx/src/BetheBlochEquationDedxSimTool.cpp, Simulation/DetSimSD/src/DriftChamberSensDetTool.cpp, Simulation/DetSimSD/src/DriftChamberSensitiveDetector.cpp
=> WIP: initialize the SD so that geant4 will invoke the correct Drift Chamber SD

build-k4.sh
Remove the unused code in the build script. See PR #55.
=> WIP: remove the unused code to get the CLHEP directory.

Digitisers/DCHDigi/CMakeLists.txt, Digitisers/DCHDigi/src/DCHDigiAlg.cpp, Digitisers/DCHDigi/src/DCHDigiAlg.h
=> WIP: updating DCHDigi

Examples/options/tut_detsim_SDT.py, Generator/src/GtGunTool.cpp, Generator/src/GtGunTool.h, Simulation/DetSimCore/src/G4PrimaryCnvTool.cpp
Usage in python script:
```python
gun.PositionXs = [100.] # mm
gun.PositionYs = [100.] # mm
gun.PositionZs = [0.] # mm
```
=> WIP: support custom position in particle gun.

Digitisers/G2CDArbor/CMakeLists.txt, Digitisers/G2CDArbor/src/G2CDArborAlg.cpp, Digitisers/G2CDArbor/src/G2CDArborAlg.h, Digitisers/G2CDArbor/src/cellIDDecoder.h, Examples/options/edm4hep_read.py
Migration of G2CDArbor from Marlin to CEPCSW. The name of new algorithm is G2CDArborAlg.
cellIDDecoder is from Marlin and needed to be replaced by DD4Hep in future.
=> Migration of G2CDArbor

Reconstruction/Tracking/CMakeLists.txt, Reconstruction/Tracking/src/Clupatra/ClupatraAlg.cpp, Reconstruction/Tracking/src/Clupatra/ClupatraAlg.h, Reconstruction/Tracking/src/Clupatra/NNClusterer.h, Reconstruction/Tracking/src/Clupatra/RuntimeMap.h, Reconstruction/Tracking/src/Clupatra/TrackingHelper.h, Reconstruction/Tracking/src/Clupatra/clupatra_new.cpp, Reconstruction/Tracking/src/Clupatra/clupatra_new.h
The Clupatra code is test to generate the same results as the Marlin.
There are still two issues.
+ Uses global variables that pollutes the project.
+ Have memory leak. 
Despite having these issues we prefer to merge these workable codes to the master and fix the issues later.
=> Add initial commit of Clupatra

Detector/DetDriftChamber/CMakeLists.txt, Detector/DetDriftChamber/compact/det.xml, Detector/DetDriftChamber/src/driftchamber/DriftChamber.cpp, Detector/DetSegmentation/DetSegmentation/GridDriftChamber.h, Detector/DetSegmentation/src/GridDriftChamber.cpp
Input parameters during geometry construction, and divide cells into each layer according to these parameters to obtain cellID.
=> The segmentation is divided and the cellID is obtained.

Digitisers/DCHDigi/CMakeLists.txt, Digitisers/DCHDigi/src/DCHDigiAlg.cpp, Digitisers/DCHDigi/src/DCHDigiAlg.h, Examples/options/tut_detsim_digi_SDT.py
Update DCHDigi for using correct wire position from DDSegmentation::GridDriftChamber
Fixes #62
=> Update DCHDigi for using correct wire position from DDSegmentation::GridDriftChamber

Examples/options/LCIO_read_pan.py, Examples/options/tut_detsim_pandora.py, Reconstruction/PFA/Pandora/GaudiPandora/include/PandoraPFAlg.h, Reconstruction/PFA/Pandora/GaudiPandora/src/CaloHitCreator.cpp, Reconstruction/PFA/Pandora/GaudiPandora/src/PandoraPFAlg.cpp
Replaced ROOT Tree by NtupleSvc in GaudiPandora
=> Replaced ROOT Tree by NtupleSvc in GaudiPandora

Service/TrackSystemSvc/src/MarlinKalTestTrack.cc
* patch for missing update in PR #70
=> Rec: add available protection for MarlinKalTestTrack

Reconstruction/PFA/Pandora/GaudiPandora/include/Utility.h, Reconstruction/PFA/Pandora/GaudiPandora/src/GeometryCreator.cpp, Reconstruction/PFA/Pandora/GaudiPandora/src/PandoraPFAlg.cpp, Reconstruction/PFA/Pandora/GaudiPandora/src/TrackCreator.cpp, Reconstruction/PFA/Pandora/GaudiPandora/src/Utility.cpp
Support pandora to get CEPCv4 tracker geometry info from dd4hep.
=> Support pandora to get CEPCv4 tracker geometry info from dd4hep

Analysis/TotalInvMass/CMakeLists.txt, Analysis/TotalInvMass/src/TotalInvMass.cc, Analysis/TotalInvMass/src/TotalInvMass.hh, Examples/options/tut_analysis_TotalInvMass.py
=> WIP: migrating TotalInvMass from Marlin to Gaudi.

Examples/options/tut_detsim_digi_truthTracker_SDT.py, Reconstruction/Tracking/CMakeLists.txt, Reconstruction/Tracking/src/TruthTracker/TruthTrackerAlg.cpp, Reconstruction/Tracking/src/TruthTracker/TruthTrackerAlg.h
Add TruthTrackAlg to store Track and TrakerHit for drift chamber tracking for single track case. dE/dx is missing in the Track. ReconstructedParticle is missing.
=> Add TruthTrackerAlg for DC

Detector/DetCEPCv4/compact/Beampipe_o1_v01_01.xml, Detector/DetCEPCv4/compact/CepC_v4-onlyTracker.xml, Detector/DetCEPCv4/compact/envelope_defs.xml, Detector/DetCEPCv4/compact/ftd_cepc.xml, Detector/DetCEPCv4/compact/services_defs.xml, Detector/DetCEPCv4/compact/top_defs.xml, Detector/DetCEPCv4/compact/tpc10_01.xml, Detector/DetCEPCv4/src/calorimeter/SEcal05_Barrel.cpp
* fix overlap between  VXD layer and VXD envelope, in FTD, in beam pipe
* change face of TPC walls, G4_Al->G4_KAPTON->g10->G4_AIR->g10->G4_KAPTON->G4_Cu  <==>  G4_Cu->G4_KAPTON->g10->G4_AIR->g10->G4_KAPTON->G4_Al
* change direction of shift of stave
* change constan field to overlay field: 3T ==> 3T (inside of coil) and -1.33716T (outside of coil)
=> SIM: CEPC_v4 geometry update

Detector/DetSegmentation/DetSegmentation/GridDriftChamber.h, Detector/DetSegmentation/src/GridDriftChamber.cpp
=> Modify naming error

.ci/github/Singularity, .ci/github/setup-github-runner.sh
In a machine with root permission and Singularity installed, you can build the image:
```
$ sudo singularity build github-runner.sif Singularity
```
Then, use script setup-github-runner.sh to create or start new instances.
=> WIP: add the github runner related scripts.

Detector/DetDriftChamber/compact/det.xml, Detector/DetDriftChamber/src/driftchamber/DriftChamber.cpp
Put a signal wire in the center of each cell on each layer,
=> Put the signal wire

Examples/src/Edm4hepTest/Edm4hepReadDCAlg.cpp, Examples/src/Edm4hepTest/Edm4hepReadDCAlg.h, Simulation/DetSimAna/src/Edm4hepWriterAnaElemTool.cpp
* The association between tracker hits and primary particles are missing. In this PR, the association is setup.
* Add a testing algorithm to test the association.
=> WIP: associate the tracker hit and the primary particle

Simulation/DetSimAna/src/Edm4hepWriterAnaElemTool.cpp
This should fix the issue #97 .
=> WIP: store the primary particle's position and momentum at endpoint

Examples/options/tut_detsim_digi_truthTracker_SDT_dedx.py, Reconstruction/DCHDedx/src/RecDCHDedxAlg.cpp, Simulation/DetSimDedx/CMakeLists.txt, Simulation/DetSimDedx/src/BetheBlochEquationDedxSimTool.cpp, Simulation/DetSimDedx/src/BetheBlochEquationDedxSimTool.h, Simulation/DetSimDedx/src/DummyDedxSimTool.cpp, Simulation/DetSimDedx/src/GFDndxSimTool.cpp, Simulation/DetSimDedx/src/GFDndxSimTool.h, Simulation/DetSimInterface/DetSimInterface/IDedxSimTool.h
Add Interface and tool for dN/dx
The GFDndxSimTool is used for dndx sampling based on betagamma value.
=> add Interface and tool for dN/dx

Simulation/DetSimAna/src/Edm4hepWriterAnaElemTool.cpp, Simulation/DetSimAna/src/Edm4hepWriterAnaElemTool.h
In Chengdong's PR #103, the HCAL output collections are not registered. In this PR, fix the problem.
=> WIP: register HCal simulation output.

Detector/DetCEPCv4/CMakeLists.txt, Detector/DetCEPCv4/compact/Beampipe_o1_v01_01.xml, Detector/DetCEPCv4/compact/CepC_v4-onlyTracker.xml, Detector/DetCEPCv4/compact/CepC_v4.xml, Detector/DetCEPCv4/compact/SHcalRpc01_EndcapRing_01.xml, Detector/DetCEPCv4/compact/Yoke05_Barrel.xml, Detector/DetCEPCv4/compact/Yoke05_Endcaps.xml, Detector/DetCEPCv4/compact/coil03.xml, Detector/DetCEPCv4/compact/envelope_defs.xml, Detector/DetCEPCv4/compact/top_defs.xml, Detector/DetCEPCv4/compact/yoke_defs.xml, Detector/DetCEPCv4/src/calorimeter/SHcalRpc01_Endcaps.cpp, Detector/DetCEPCv4/src/calorimeter/Yoke05_Barrel.cpp, Detector/DetCEPCv4/src/calorimeter/Yoke05_Endcaps.cpp, Detector/DetCEPCv4/src/other/SCoil02_geo.cpp, Simulation/DetSimAna/src/Edm4hepWriterAnaElemTool.cpp, Simulation/DetSimAna/src/Edm4hepWriterAnaElemTool.h
* add SCoil02 from Mokka
* [Detector/DetCEPCv4/src/other/SCoil02_geo.cpp](Detector/DetCEPCv4/src/other/SCoil02_geo.cpp)
* add Yoke05 from Mokka
* [Detector/DetCEPCv4/src/calorimeter/Yoke05_Barrel.cpp](Detector/DetCEPCv4/src/calorimeter/Yoke05_Barrel.cpp)
* [Detector/DetCEPCv4/src/calorimeter/Yoke05_Endcaps.cpp](Detector/DetCEPCv4/src/calorimeter/Yoke05_Endcaps.cpp)
* fix some overlap between old option of other sub-detectors and coil/yoke
* add collection for COIL and Muon converter in `Edm4hepWriterAnaElemTool`
=> SIM: and coil and yoke module for CEPCv4

Digitisers/G2CDArbor/src/G2CDArborAlg.cpp, Digitisers/SimHitMerge/src/SimHitMergeAlg.cpp, Digitisers/SimHitMerge/src/SimHitMergeAlg.h, Reconstruction/PFA/Pandora/GaudiPandora/include/GeometryCreator.h, Reconstruction/PFA/Pandora/GaudiPandora/include/Utility.h, Reconstruction/PFA/Pandora/GaudiPandora/src/CaloHitCreator.cpp, Reconstruction/PFA/Pandora/GaudiPandora/src/GeometryCreator.cpp, Reconstruction/PFA/Pandora/GaudiPandora/src/PandoraPFAlg.cpp, Reconstruction/PFA/Pandora/GaudiPandora/src/TrackCreator.cpp, Reconstruction/PFA/Pandora/GaudiPandora/src/Utility.cpp
adding ECRing and HCAL geometry reading function from dd4hep for Pandora
add a sanity_check part for SimHitMergeAlg
=> update Pandora detector geometry info reading

Detector/DetCEPCv4/compact/SEcal05_siw_ECRing_01.xml, Detector/DetCEPCv4/compact/SEcal05_siw_Endcaps.xml, Detector/DetCEPCv4/compact/SHcalRpc01_Barrel_01.xml, Detector/DetCEPCv4/compact/SHcalRpc01_EndcapRing_01.xml, Detector/DetCEPCv4/compact/SHcalRpc01_Endcaps_01.xml, Detector/DetCEPCv4/compact/ecal_defs.xml, Detector/DetCEPCv4/src/calorimeter/SHcalRpc01_Barrel.cpp, Detector/DetCEPCv4/src/calorimeter/SHcalRpc01_EndcapRing.cpp, Detector/DetCEPCv4/src/calorimeter/SHcalRpc01_Endcaps.cpp
The cell offset of SEcal05_siw_Endcaps， SEcal05_siw_ECRing_01， and HcalRpc01_Barrel_01 are set in order to keep the cell position to be same with  Mokka's.
=> update CEPCv4 ECAL and HCAL xml

Detector/DetCRD/compact/CRD_common_v01/DC_Simple_v01_01.xml, Detector/DetCRD/compact/CRD_o1_v01/CRD_Dimensions_v01_01.xml, Detector/DetDriftChamber/compact/det.xml, Detector/DetDriftChamber/src/driftchamber/DriftChamber.cpp
Hi, @mirguest , @ihepzhangyao ,I have improved the number control of the drift chamber，among them, the meaning of the parameter is：
0:inner chamber + outer chamber;
1:only inner chamber;
2:only outer chamber; 
I hope you will provide valuable comments on the changes I made, thank you.
=> Control the number of drift chambers

cmake/FindHepMC.cmake
=> WIP: add FindHepMC.cmake.

Detector/DetCRD/compact/CRD_common_v01/Coil_Simple_v01_01.xml, Detector/DetCRD/compact/CRD_common_v01/DC_Simple_v01_01.xml, Detector/DetCRD/compact/CRD_common_v01/FTD_SimpleStaggered_v01_02.xml, Detector/DetCRD/compact/CRD_common_v01/Hcal_Rpc_Barrel_v01_01.xml, Detector/DetCRD/compact/CRD_common_v01/Hcal_Rpc_Endcaps_v01_01.xml, Detector/DetCRD/compact/CRD_common_v01/SET_SimplePlanar_v01_02.xml, Detector/DetCRD/compact/CRD_common_v01/SIT_SimplePixel_v01_01.xml, Detector/DetCRD/compact/CRD_common_v01/Yoke_Barrel_v01_01.xml, Detector/DetCRD/compact/CRD_common_v01/Yoke_Endcaps_v01_01.xml, Detector/DetCRD/compact/CRD_o1_v02/CRD_Dimensions_v01_02.xml, Detector/DetCRD/compact/CRD_o1_v02/CRD_o1_v02.xml, Detector/DetCRD/compact/README.md
* correct strip angle (7 degree) for SIT
* add CEPC_v4 like Coil, Hcal, Yoke, will switch to once  new modules ready
* SCoil02
* SHcalRpc01_Barrel and SHcalRpc01_Endcaps
* Yoke05_Barrel and Yoke05_Endcaps
* fix overlap of DC
* SDT_half_length should be half length not include endcap plate according to construction
* re-define some chamber parameters
* implement CRD_o1_v02, for two pixel SIT layers inside DC
=> SIM：improve CRD geometry

Reconstruction/PFA/Pandora/GaudiPandora/include/PandoraPFAlg.h, Reconstruction/PFA/Pandora/GaudiPandora/src/CaloHitCreator.cpp, Reconstruction/PFA/Pandora/GaudiPandora/src/PandoraPFAlg.cpp
The Stave number for HCAL and Muon calorimeters are corrected
Fix potential break when saving ntuple
=> update Pandora to use correct Stave number

Detector/DetCRD/CMakeLists.txt, Detector/DetCRD/src/Tracker/SiTrackerSkewRing_v01_geo.cpp
a constructor for tracpezoidal planar silicon tracker with optional skew angle with rphi plane:
//              __________________                                                                                                                                                             
//               \           |           /                                                                                                                                                             
//                 \         |         /                                                                                                                                                              
//                   \       |       / …
=> SIM: add first version of SiTrackerSkewRing

Detector/DetCRD/CMakeLists.txt, Detector/DetCRD/compact/CRD_common_v01/Ecal_Crystal_Barrel_v01_01.xml, Detector/DetCRD/src/Calorimeter/CRDEcal_v01.cpp
Update the crystal Ecal geometry file to: 
* fix the large memory usage problem for #Issue156
* group the bars in a super-cell for reconstruction
=> Modify Ecal geometry

Analysis/DumpEvent/CMakeLists.txt, Analysis/DumpEvent/src/DumpMCParticleAlg.cpp, Analysis/DumpEvent/src/DumpMCParticleAlg.h, Analysis/DumpEvent/src/DumpTrackAlg.cpp, Analysis/DumpEvent/src/DumpTrackAlg.h
* dump into TTree (ntuple) in root file, and then events can be analysed in ROOT macro. 
* for different collections with same type (such as Track), overload the algorithm like as following:
from Configurables import DumpMCParticleAlg
dumpMC = DumpMCParticleAlg("DumpMC")
dumpMC.MCParticleCollection = "MCParticle"
dumpMC.OutputLevel = DEBUG
from Configurables import DumpTrackAlg
dumpFu = DumpTrackAlg("DumpFu")
dumpFu.TrackCollection = "MarlinTrkTracks"
#dumpFu.OutputLevel = DEBUG                                                                                                                                                                 
dumpCl = DumpTrackAlg("DumpCl")
dumpCl.TrackCollection = "ClupatraTracks"
#dumpCl.OutputLevel = DEBUG …
=> Data: algorithm to dump event infos to TTree format

cmake/CEPCSWDependencies.cmake
=> WIP: add a new dependency Garfield.

Reconstruction/PFA/Pandora/GaudiPandora/include/CaloHitCreator.h, Reconstruction/PFA/Pandora/GaudiPandora/include/MCParticleCreator.h, Reconstruction/PFA/Pandora/GaudiPandora/include/TrackCreator.h, Reconstruction/PFA/Pandora/GaudiPandora/src/CaloHitCreator.cpp, Reconstruction/PFA/Pandora/GaudiPandora/src/MCParticleCreator.cpp, Reconstruction/PFA/Pandora/GaudiPandora/src/TrackCreator.cpp
#208 this problem is fixed! The reason for the errors is that the reference (&) is missing for some cases when using auto.
=> fix Pandora errors by using reference together with auto

Detector/DetCEPCv4/CMakeLists.txt, Detector/DetCEPCv4/src/calorimeter/SHcalSc04_Barrel_v04.cpp, Detector/DetCEPCv4/src/calorimeter/SHcalSc04_Endcaps_v01.cpp, Detector/DetCRD/compact/CRD_common_v01/SHcalSc04_Barrel_v04_01.xml, Detector/DetCRD/compact/CRD_common_v01/SHcalSc04_Endcaps_v01_01.xml, Detector/DetCRD/compact/Standalone/Standalone-SHcalSc04.xml
* Migrate AHcal from lcgeo.
* SHcalSc04_Barrel_v04_01.xml and SHcalSc04_Endcaps_v01_01.xml show an example for SD-A Hcal with RPC and scintillator together. Ony one can be kept by option.
=> GEO: add AHcal module

Digitisers/DCHDigi/src/DCHDigiAlg.cpp
As in https://github.com/key4hep/EDM4hep/pull/139
=> remove Edx from trackerhit as in edm4hep

Utilities/KiTrack/src/Tools/Fitter.cc
One more change needed for edm4hep v00-05, I forgot to mention this one before, apologies for that.
=> edm4hep::TrackState: add dummy value for time

Simulation/DetSimAna/CMakeLists.txt, Simulation/DetSimAna/src/Edm4hepWriterAnaElemTool.cpp, Simulation/DetSimAna/src/ExampleAnaElemTool.cpp, Simulation/DetSimSD/CMakeLists.txt, Simulation/DetSimSD/include/DetSimSD/DDG4SensitiveDetector.h, Simulation/DetSimSD/include/DetSimSD/Geant4Hits.h, Simulation/DetSimSD/src/DDG4SensitiveDetector.cpp, Simulation/DetSimSD/src/Geant4Hits.cpp, build-k4.sh
=> Import DDG4/Geant4Hits to CEPCSW

Generator/src/GenPrinter.cpp, Simulation/DetSimAna/src/Edm4hepWriterAnaElemTool.cpp, Simulation/DetSimAna/src/Edm4hepWriterAnaElemTool.h, Simulation/DetSimCore/src/G4PrimaryCnvTool.cpp, Simulation/DetSimGeom/src/AnExampleDetElemTool.cpp
As requested in #234 , mute some outputs.
=> Mute the stdout in simulation

.github/workflows/main.yml, build.sh, run.sh, setup.sh
Note: 
* GEAR is migrated from IHEP git repo to GitHub: https://github.com/cepc/GEAR
=> Update LCG externals from 101.0.1 to 103.0.0

Utilities/DataHelper/include/DataHelper/Navigation.h, Utilities/DataHelper/src/Navigation.cpp
See https://github.com/cepc/CEPCSW/pull/262/files#r1499264419
=> According to comment from Thomas, use (0, 10, 5)
