Detector/DetCEPCv4/compact/CepC_v4-onlyTracker.xml, Simulation/DetSimGeom/src/AnExampleDetElemTool.cpp
As the B-field is missing in the CEPCSW, I add an example to setup a uniform B-field.
Ref:
* [DD4hep B-field example](https://github.com/AIDASoft/DD4hep/blob/master/examples/ClientTests/compact/MagnetFields.xml)
* [Geant4 uniform field](https://github.com/Geant4/geant4/blob/master/source/geometry/magneticfield/include/G4UniformMagField.hh)
=> Setup B-Field in Simulation

README.md
As the external LCG 97.0.2 is built with SL6, we need to start a container to run the current CEPCSW.
=> Add the instruction of Singularity container

Detector/DetDriftChamber/CMakeLists.txt, Detector/DetDriftChamber/compact/det.xml, Detector/DetDriftChamber/compact/elements.xml, Detector/DetDriftChamber/compact/materials.xml, Detector/DetDriftChamber/src/driftchamber/DriftChamber.cpp, Simulation/DetSimAna/src/Edm4hepWriterAnaElemTool.cpp, Simulation/DetSimAna/src/Edm4hepWriterAnaElemTool.h
* The dimensions are defined as the constants (See commit 2d3a664c9e47106d56d127f5708a066ec17a7b1f)
+ radii: 235 mm, 1716 mm
+ z: -2225 mm, 2225 mm
+ radii: 235 mm, 909 mm
+ z: -2225 mm, 2225 mm
+ radii: 1085 mm, 1716 mm
+ z: -2225 mm, 2225 mm
=> WIP: development of Drift Chamber for CEPC

Utilities/KalDet/CMakeLists.txt
This PR will fix the issue #19 : the KalTest directory is hard coded in the current CMakeLists.txt
=> WIP: Fixed the hard-code problem.

Detector/DetCEPCv4/compact/vxd07.xml, Detector/DetCEPCv4/src/tracker/VXD04_geo.cpp, Reconstruction/SiliconTracking/src/ForwardTrackingAlg.cpp, Reconstruction/SiliconTracking/src/SiliconTrackingAlg.cpp, Reconstruction/SiliconTracking/src/SpacePointBuilderAlg.cpp, Reconstruction/SiliconTracking/src/SpacePointBuilderAlg.h, Reconstruction/SiliconTracking/src/TrackSubsetAlg.cpp, Service/TrackSystemSvc/src/MarlinKalTestTrack.cc
* Detector
* add barrelside region into cellID (compact file and geo file)
* in MokkaC and Marlin version of CEPC_v4, VXD's side fixed as 0, in order to let digitization and reconstruction algorithms compatible to old data, change side value to 0 too. So, additional id region (barrelside) needs to distinct the two placed volumes (side=+1,-1 before modification), to avoid crash caused by same cellID for two placed volumes.  
* change endplate_inner_radius to let CryostatAlInnerR equal to Mokka's CEPC_v4 (compact file)
* SiliconTracking
* move createAndPut to begin of execute() (*.cpp )
* change type of parameters (SpacePointBuilderAlg.h)
* TrackSystemSvc
* change debug message (MarlinKalTestTrack.cc)
=> Fix bug for silicon-tracking

Detector/GeoSvc/CMakeLists.txt, Digitisers/SimpleDigi/CMakeLists.txt, Reconstruction/PFA/Pandora/GaudiPandora/CMakeLists.txt, Reconstruction/PFA/Pandora/MatrixPandora/CMakeLists.txt, Reconstruction/SiliconTracking/CMakeLists.txt, Service/GearSvc/CMakeLists.txt, Service/TrackSystemSvc/CMakeLists.txt, Utilities/KalDet/CMakeLists.txt, build-k4.sh
This PR will fix the issue #53. 
BTW: The GEAR deployed at IHEP is modified a bit, adding following lines in `GEARConfig.cmake`:
```
set(GEAR_LIBRARIES)
list(APPEND GEAR_LIBRARIES ${GEAR_LIBRARY_DIR}/libgearsurf.so)
list(APPEND GEAR_LIBRARIES ${GEAR_LIBRARY_DIR}/libgear.so)
list(APPEND GEAR_LIBRARIES ${GEAR_LIBRARY_DIR}/libgearxml.so)
```
=> WIP: Support both LCG and k4spack stack for CEPCSW 

Digitisers/SimpleDigi/CMakeLists.txt, Reconstruction/PFA/Pandora/GaudiPandora/CMakeLists.txt, Service/TrackSystemSvc/CMakeLists.txt, Utilities/KalDet/CMakeLists.txt, Utilities/KiTrack/CMakeLists.txt, build-k4.sh
This should fix the problem mentioned in https://github.com/key4hep/k4-spack/pull/73#discussion_r503340120. The solution is remove explict dependencies.
=> WIP: the FindCLHEP from Gaudi is used when using spack. Just remove the explict dependencies on CLHEP.

Detector/DetCEPCv4/CMakeLists.txt, Detector/DetCEPCv4/compact/Beampipe_o1_v01_01.xml, Detector/DetCEPCv4/compact/CepC_v4-onlyTracker.xml, Detector/DetCEPCv4/compact/README.md, Detector/DetCEPCv4/compact/SEcal05_siw_Barrel.xml, Detector/DetCEPCv4/compact/SEcal05_siw_ECRing.xml, Detector/DetCEPCv4/compact/SEcal05_siw_Endcaps.xml, Detector/DetCEPCv4/compact/ecal_defs.xml, Detector/DetCEPCv4/compact/envelope_defs.xml, Detector/DetCEPCv4/compact/ftd_cepc.xml, Detector/DetCEPCv4/compact/sit_simple_planar_sensors_01.xml, Detector/DetCEPCv4/compact/top_defs.xml, Detector/DetCEPCv4/compact/top_defs_CepC_v04.xml, Detector/DetCEPCv4/compact/tpc10_01.xml, Detector/DetCEPCv4/compact/tube_defs.xml, Detector/DetCEPCv4/src/calorimeter/SEcal05_Barrel.cpp, Detector/DetCEPCv4/src/calorimeter/SEcal05_ECRing.cpp, Detector/DetCEPCv4/src/calorimeter/SEcal05_Endcaps.cpp, Detector/DetCEPCv4/src/calorimeter/SEcal05_Helpers.cpp, Detector/DetCEPCv4/src/tracker/FTD_cepc_geo.cpp, Detector/DetCEPCv4/src/tracker/SIT_Simple_Planar_geo.cpp
* FTD
* update parameters of hole, switch FTD_Simple_Staggered to FTD_cepc, because FTD_Simple_Staggered uses same edge at transverse and radial. In CEPC_v4, they are different.
* update relative parameters of tube to calculate it inner radius 
* reduce 7 layers to 5 layers same as CEPC_v4
* TPC
* update parameters of wall and cathode
* SIT
* switch pixel to strip (CEPC_v4 used, fix)
* Tube
* update to let z=0-700mm same as CEPC_v4, but left >700mm because new type of pipe used in CEPC_v4 and the design has been replaced. 0-700mm is enough for most of physics study.
* Ecal
* modification
* recover support material to g10
* set preShower option to 1
* fix difference of face structure
* set grid size of segmentation as 10.1667*mm. In current option and MokkaC, the dimension z of wafer is …
=> upgrade tracker&ecal to match CEPC_v4

Reconstruction/Tracking/src/Clupatra/NNClusterer.h
Clupatra/clupatra_new.cpp calls not in range with negative number and
current unsigned template causes compile error.
=> fix not in range compile error

Digitisers/SimpleDigi/src/PlanarDigiAlg.cpp, Reconstruction/SiliconTracking/src/ForwardTrackingAlg.cpp, Reconstruction/SiliconTracking/src/SiliconTrackingAlg.cpp, Reconstruction/SiliconTracking/src/SpacePointBuilderAlg.cpp, Reconstruction/SiliconTracking/src/TrackSubsetAlg.cpp, Service/TrackSystemSvc/TrackSystemSvc/ITrackSystemSvc.h, Service/TrackSystemSvc/src/TrackSystemSvc.cpp, Service/TrackSystemSvc/src/TrackSystemSvc.h, Utilities/DataHelper/src/TrackExtended.cc, Utilities/KalDet/src/ild/common/MaterialDataBase.cc, Utilities/KalDet/src/ild/ftd/ILDFTDKalDetector.cc, Utilities/KalDet/src/ild/set/ILDSETKalDetector.cc, Utilities/KalDet/src/ild/sit/ILDSITKalDetector.cc, Utilities/KalDet/src/ild/support/ILDSupportKalDetector.cc, Utilities/KalDet/src/ild/tpc/ILDTPCKalDetector.cc, Utilities/KalDet/src/ild/vxd/ILDVXDKalDetector.cc
* separate common track system by oneself
* Issue: options are covered with each other in algorithms, because of using a common track system `_trksystem =  _trackSystemSvc->getTrackSystem();`
* create special track system according ptr now: `_trksystem =  _trackSystemSvc->getTrackSystem(this);`; accordingly, insert ptr of track system into map in TrackSystemSvc
* additional fix:
* `UTIL::BitSet32( trkhit.getType() )[ ]` here should be bit order, 31->3, since 8 denotes LCIO's TrackerHitPlane now, it will be updated a common constant.
* if `auto track = trk_col->create()` used, a null track will create although no track found, fix by `trk_col->push_back(track)` method
* fix error to return unavaible TrackerHit
* Issue: unavailble Track cause crash sometime while testing FullLDCTrackingAlg …
=> Fix tracking error

Digitisers/DCHDigi/CMakeLists.txt, Digitisers/G2CDArbor/CMakeLists.txt, Digitisers/SimpleDigi/CMakeLists.txt, Generator/CMakeLists.txt, Reconstruction/Digi_Calo/CMakeLists.txt, Reconstruction/PFA/Pandora/GaudiPandora/CMakeLists.txt, Reconstruction/PFA/Pandora/MatrixPandora/CMakeLists.txt, Service/TrackSystemSvc/CMakeLists.txt, Utilities/KalDet/CMakeLists.txt, Utilities/KiTrack/CMakeLists.txt
In previous PR #55, I remove the dependencies on CLHEP. However, some developers still need to use the CLHEP. Current solution is using CONFIG file instead of FindCLHEP.
=> Using CONFIG option in find_package for the package CLHEP

Reconstruction/Tracking/Tracking/TrackingHelper.h, Reconstruction/Tracking/src/Clupatra/ClupatraAlg.cpp, Reconstruction/Tracking/src/Clupatra/ClupatraAlg.h, Reconstruction/Tracking/src/Clupatra/clupatra_new.cpp, Reconstruction/Tracking/src/Clupatra/clupatra_new.h
* update track system interface according to #68 and apply filter option input from python
* add Segments output
* issue: if not add, Track link will meet crash?
* change `ConstTrack` to `Track`,  because only `Track` class can call `addToTracks(...)`
* TrackingHelper.h
* move to [Reconstruction/Tracking/Tracking](Reconstruction/Tracking/Tracking) , since FullLDCTrackingAlg will also use it
* clupatra_new::operator()
* issue: sometime while applying ClupatraAlg on CEPCSW simulated and TPCDigiAlg digitized data, cannot get available TrackerHit object while `mtrk->getTrackerHitAtPositiveNDF( last_constrained_hit );`
* add protection and TODO: check how this problem causes
=> update ClupatraAlg and fix its runtime error

Reconstruction/Tracking/CMakeLists.txt, Reconstruction/Tracking/src/FullLDCTracking/FullLDCTrackingAlg.cpp, Reconstruction/Tracking/src/FullLDCTracking/FullLDCTrackingAlg.h
* Track merger for TPC tracks （by ClupatraAlg） and Silicon tracks （by TrackSubsetAlg）, and output merged tracks
* Workable following CEPCSW simulation and migrated PlanarDigiAlg, TPCDigiAlg, SpacePointBuilderAlg, SiliconTrackingAlg, ForwardTrackingAlg, TrackSubsetAlg, ClupatraAlg
* TODO:
* sometime TPC track's TrackState is unavailable, add protection and replaced by Si tracks' now, since the track state `pre_fit` is taken as initial input. But why happen? Need next check.
try{
pre_fit = getTrackStateAt(tpcTrack->getTrack(), 3/*lcio::TrackState::AtLastHit*/);`
}
catch(std::runtime_error& e){
error() << e.what() << " should be checked (TPC track)" << endmsg;
try{
pre_fit = getTrackStateAt(siTrack->getTrack(), 3/*lcio::TrackState::AtLastHit*/);
}
catch(std::runtime_error& e){
error() << …
=> import FullLDCTracking based on Mingrui's code

Detector/DetDriftChamber/compact/det.xml, Detector/DetDriftChamber/src/driftchamber/DriftChamber.cpp, Detector/DetSegmentation/DetSegmentation/GridDriftChamber.h, Detector/DetSegmentation/src/GridDriftChamber.cpp
In the process of digitization, it was discovered that the wire position was incorrectly obtained, which caused the DCA to be too large.
After modifying phiFromXY(), the DCA value is normal.
=> Fixed the phiFromXY() function to subtract a pai

Examples/options/LCIO_read_pan.py, Examples/options/tut_detsim_pandora.py, Reconstruction/PFA/Pandora/GaudiPandora/CMakeLists.txt, Reconstruction/PFA/Pandora/GaudiPandora/include/CaloHitCreator.h, Reconstruction/PFA/Pandora/GaudiPandora/include/GeometryCreator.h, Reconstruction/PFA/Pandora/GaudiPandora/include/PandoraPFAlg.h, Reconstruction/PFA/Pandora/GaudiPandora/include/TrackCreator.h, Reconstruction/PFA/Pandora/GaudiPandora/include/Utility.h, Reconstruction/PFA/Pandora/GaudiPandora/src/CaloHitCreator.cpp, Reconstruction/PFA/Pandora/GaudiPandora/src/GeometryCreator.cpp, Reconstruction/PFA/Pandora/GaudiPandora/src/PandoraPFAlg.cpp, Reconstruction/PFA/Pandora/GaudiPandora/src/TrackCreator.cpp, Reconstruction/PFA/Pandora/GaudiPandora/src/Utility.cpp
Update GaudiPandora to support read Geo info from DD4HEP and use decoder from DD4HEP
Now, in option files, one can choose if get Geo information from DD4HEP or from Gear. Also one can choose if use decoder from DD4HEP (see Examples/options/tut_detsim_pandora.py as am example)
=> Update GaudiPandora to support read Geo info and get decoder from DD4HEP

Digitisers/G2CDArbor/src/G2CDArborAlg.cpp, Digitisers/G2CDArbor/src/G2CDArborAlg.h, Digitisers/SimHitMerge/CMakeLists.txt, Digitisers/SimHitMerge/src/SimHitMergeAlg.cpp, Digitisers/SimHitMerge/src/SimHitMergeAlg.h, Examples/options/LCIO_read_G2CD.py, Examples/options/tut_detsim_G2CD.py
Hi @mirguest @LinghuiWuIHEP
I add one alg (SimHitMergeAlg) for merging simcalorimeterhit from simulation by cell id. Now the G2CDArborAlg can use the data after SimHitMergeAlg for processing digitization for CEPCSW simulated data, just like processing simulation data produced by Mokka.
Besides, I correct the G2CDArborAlg a bit (mainly add a selection of readout, modify the layer number). Could you review the changes?
Best,
Wenxing
=> Add SimHitMergeAlg and update G2CDArborAlg

Simulation/DetSimGeom/src/AnExampleDetElemTool.cpp, Simulation/DetSimGeom/src/AnExampleDetElemTool.h, Simulation/DetSimSD/CMakeLists.txt, Simulation/DetSimSD/DetSimSD/DDG4SensitiveDetector.h, Simulation/DetSimSD/src/DDG4SensitiveDetector.cpp, Simulation/DetSimSD/src/TimeProjectionChamberSensDetTool.cpp, Simulation/DetSimSD/src/TimeProjectionChamberSensDetTool.h, Simulation/DetSimSD/src/TimeProjectionChamberSensitiveDetector.cpp, Simulation/DetSimSD/src/TimeProjectionChamberSensitiveDetector.h
* Issue
* while using default dd4hep tracker SD, reconstructed results (resolution, pull distribution) are different with Marlin's
* Implemetation
* new TimeProjectionChamberSensitiveDetector
* create TimeProjectionChamberSensDetTool to control TPC SD type and import parameters from DD4hep object or job option, possible to switch SD type
* TODO
* set hit-relative secondary particle to be saved
=> SIM: add special TPC SD migrated from Marlin processor

Generator/src/GtGunTool.cpp
In the previous particle gun, the charge is not set.
=> WIP: save charge of particle in particle gun tool.

Reconstruction/Tracking/src/Clupatra/ClupatraAlg.cpp, Reconstruction/Tracking/src/Clupatra/RuntimeMap.h
All data objects of a previous event are removed at the beginning of the next event. So we should clear the map as soon as possible, but not clear it until next event.
=> clear temporary maps at the end of the algorithm

Detector/DetDriftChamber/compact/det.xml, Detector/DetSegmentation/src/GridDriftChamber.cpp, Examples/options/tut_detsim_SDT.py, Simulation/DetSimCore/src/DetSimAlg.cpp, Simulation/DetSimCore/src/DetSimAlg.h, Simulation/DetSimCore/src/DetectorConstruction.cpp, Simulation/DetSimCore/src/DetectorConstruction.h, Simulation/DetSimFastModel/CMakeLists.txt, Simulation/DetSimFastModel/src/DummyFastSimG4Model.cpp, Simulation/DetSimFastModel/src/DummyFastSimG4Model.h, Simulation/DetSimFastModel/src/DummyFastSimG4Tool.cpp, Simulation/DetSimFastModel/src/DummyFastSimG4Tool.h, Simulation/DetSimInterface/DetSimInterface/IFastSimG4Tool.h
This PR contains
* Introduce a new interface for the fast simulation based on the Geant4 fast/parameterization simulation model.
* A dummy fast simulation model
* The dummy tool is used to associate Region and Fast simulation model
* The dummy model will kill all the charged secondaries in DriftChamberRegion.
* Prepare for the Garfield integration. 
* The dedicated region "DriftChamberRegion" is created. 
* The region will be used both for the fast simulation model and the PAI model in EM.
* In DD4hep, the limits could be also set for the region. But in this PR, the limits are not set.
* The additional physics list are registered into DetSimCore.
* In the future, maybe introduce an interface to manage the physics list.
=> WIP: Create an example of fast simulation in CEPCSW

Simulation/DetSimAna/src/Edm4hepWriterAnaElemTool.cpp
Flag in particles:
* This feature is not implemented yet. If particle is decayed, then both bits are marked as 1.
Flag in hits:
=> WIP: Set flag when primary particle is decayed.

Simulation/DetSimFastModel/src/DummyFastSimG4Tool.cpp, Simulation/DetSimFastModel/src/DummyFastSimG4Tool.h
In the previous implementation, one fast sim model is only associated with one region and the region name is hard-coded. In this PR, users are allowed to set the region names as following:
```python
from Configurables import DummyFastSimG4Tool
dummy_fastsim_tool = DummyFastSimG4Tool("DummyFastSimG4Tool")
dummy_fastsim_tool.Regions = [
"DriftChamberRegion",
]
detsimalg.FastSimG4Tools = [
"DummyFastSimG4Tool"
]
```
=> WIP: allow to associate a fastsim model with multiple regions

Service/GearSvc/CMakeLists.txt, Service/GearSvc/src/GearSvc.cpp, Service/GearSvc/src/GearSvc.h, Service/TrackSystemSvc/src/MarlinKalTest.cc, Service/TrackSystemSvc/src/MarlinKalTest.h, Service/TrackSystemSvc/src/TrackSystemSvc.cpp
* move convertor from GeomSvc to GearSvc
* The redundant interfaces of GeomSvc such as getVXDParameters(), getDetParameters() and so on, are considered to obselete in future 
* GearSvc: if xml input, read from file; if not input, convert from GeomSvc
* add more convertor (SIT, SET, TPC, FTD) 
* add fake Ecal parameters as preliminary, will/should correct if calorimeter reconstruction need Gear parameters
* Note:
* for old tracking algorithm compareing to Marlin, keep use Gear parameters by convertor
* for new tracking algotithm, intensively use getDD4HepGeo() to get DD4hep object and use DD4hep extension data and surfaces
=> Geometry: move convertor from GeomSvc to GearSvc

Analysis/TrackInspect/CMakeLists.txt, Analysis/TrackInspect/src/TrackInspectAlg.cpp, Analysis/TrackInspect/src/TrackInspectAlg.h
This algorithm inspect the MCParticles and the corresponding matched tracks.
It could be used as the standard checks for tracking efficiency, track reconstruction resolution, etc.
=> Initial commit of track inspect

CMakeLists.txt, cmake/CEPCSWEnv.cmake
Because the Gaudi v35 removes the feature to create envvar for each package, this PR provides a solution to setup some necessary envvar. The cmake variable `RUN_SCRIPT_EXTRA_COMMANDS` could refer to https://twikiro.cern.ch/twiki/bin/view/LHCb/MaintainGaudiCMake315Configuration
=> WIP: set envvar to be compatible with LCG 97 and Gaudi v33/34.

Examples/options/tut_detsim.py, Examples/options/tut_detsim_SDT.py, Examples/options/tut_detsim_digi_SDT.py, Examples/options/tut_detsim_digi_fit_DC.py, Examples/options/tut_detsim_digi_truthTracker_SDT.py, Examples/options/tut_detsim_digi_truthTracker_SDT_dedx.py, Examples/options/tut_detsim_pan_matrix.py, Examples/options/tut_detsim_pandora.py, Simulation/DetSimCore/src/DetSimAlg.cpp, Simulation/DetSimCore/src/DetSimAlg.h
In https://gitlab.cern.ch/gaudi/Gaudi/-/issues/165, I report the seed is clear in Gaudi. So the current solution is to set the seed in DetSimAlg.
The major changes in Python script:
- define a seed
- Create the Random Engine with name "RndmGenSvc.Engine"
- Create the RndmGenSvc
- Set the `detsimalg.RandomSeeds = seed`
- add the RndmGenSvc in the ExtSvc
```diff
+seed = [42]
+
-rndmengine = HepRndm__Engine_CLHEP__HepJamesRandom_() # The default engine in Geant4
+rndmengine = HepRndm__Engine_CLHEP__HepJamesRandom_("RndmGenSvc.Engine") # The default engine in Geant4
rndmengine.SetSingleton = True
-rndmengine.Seeds = [42]
+rndmengine.Seeds = seed
+
+rndmgensvc = RndmGenSvc("RndmGenSvc")
+rndmgensvc.Engine = rndmengine.name()
detsimalg = DetSimAlg("DetSimAlg")
+detsimalg.RandomSeeds = seed
- …
```
=> WIP: Set the Random Seed in DetSimAlg

Detector/DetCEPCv4/compact/SHcalRpc01_Barrel_01.xml
Wenxing reported a bug on the difference of position between SimHit.getPosition() and
CellIDPositionConverter::position(Simhit.getCellID()). 
Through check, It is found that this is caused by the unmatched usage of segmentation
with geometry. This commit can fix this bug.
=> SIM: fix on option of CEPCv4 Hcal

Reconstruction/RecGenfitAlg/src/GenfitTrack.h
gcc 9.3.0 flags these as errors (-fpermissive), because a friend declaration with default arguments must also be a definition.
I suppose gcc has become less forgiving between gcc8 and gcc9, because everything still works with gcc8. Also simply removing the default arguments here doesn't break anything in the build, so I think they are provided on the call sites in any case.
Fixes key4hep/key4hep-spack#157
=> Remove default argument values from friend member functions

Digitisers/SimpleDigi/src/PlanarDigiAlg.cpp, Digitisers/SimpleDigi/src/PlanarDigiAlg.h, Utilities/DataHelper/include/DataHelper/TrackerHitHelper.h, Utilities/DataHelper/src/TrackerHitHelper.cpp
* prepare for switch cov matrix
* Plan:
* function CEPC::GetResolutionRPhi() and CEPC::GetResolutionZ() to replace hit.getCovMatrix() to get resolution for planar sensors in silicon tracking algorithm
* control to save XYZ cov matrix or RphiZ cov matrix
=> REC: add optional control for cov matrix

Simulation/DetSimSD/src/DDG4SensitiveDetector.cpp
In the latest DD4hep, the DDG4 Legacy is removed in https://github.com/AIDASoft/DD4hep/commit/a732b835fa571ba5db47e29da7d05c2eea7339b2#diff-bf9e9572dd8da09de21a1b7143d7c73189dad8ae2eb581ad2caaa216e4cc573f , which cause the build of Key4hep project failed (see issue #159). The solution is removing the related code in CEPCSW.
=> As the latest DDG4 removes DDG4Legacy, the code is updated. It will fix the issue #159

Service/GearSvc/src/GearSvc.cpp, Service/GearSvc/src/GearSvc.h
* Cryostat is optional, and if no crystat and still fill "VXDInfra" GearParameter will cause crash. No fill while no crystat will fix it.
* cheat DC parameters as TPC, maybe create driftchamber extension data will be better in future
* if extension data exists, use it
* if not exist, convert from volume directly as preliminary
=> REC: cheat DC as TPC for Gear and fix VXD error while no cryostat

Service/GearSvc/CMakeLists.txt, Service/GearSvc/src/GearSvc.cpp
Drift chamber real layers are removed in  PR#152, therefore layer number is invalid in volume. This update uses GridDriftChamber segmentation to obtain layer number, rbegin, rend and layer_width, to let job work again.
=> REC: GearSvc hot fix for GridDriftChamber segmentation

Detector/DetCEPCv4/src/tracker/SIT_Simple_Pixel_geo.cpp, Detector/DetCRD/compact/CRD_common_v01/FTD_SkewRing_v01_01.xml, Detector/DetCRD/compact/CRD_common_v01/FTD_SkewRing_v01_02.xml, Detector/DetCRD/compact/CRD_common_v01/SET_SimplePixel_v01_01.xml, Detector/DetCRD/compact/CRD_common_v01/SET_SimplePlanar_v01_01.xml, Detector/DetCRD/compact/CRD_common_v01/SIT_SimplePixel_v01_01.xml, Detector/DetCRD/compact/CRD_common_v01/SIT_SimplePixel_v01_02.xml, Reconstruction/SiliconTracking/src/SiliconTrackingAlg.cpp
* fix bug
* SiliconTrackingAlg does not work for only pixel or strip FTD hits exist
* update
* SIT_Simple_Pixel geometry module: change vis option input, and change volume prefix from fixed "SIT" to detector name (input by XML), to make possible to use it to create pixel SET
* optional sensitive thickness and support thickness, default as 0.65% of X0
* SIT_SimplePixel_v01_01.xml change to 4 layers
* new implementation preparing for new 4th conceptual detector 
*  SIT_SimplePixel_v01_02.xml for 3 layers
*  SET_SimplePixel_v01_01.xml for pixel SET
*  FTD_SkewRing_v01_01.xml for 5 layers
*  FTD_SkewRing_v01_02.xml for 4 layers
=> GEO&REC: Silicon tracker update

Detector/DetCRD/compact/CRD_common_v01/DC_Simple_v01_01.xml, Detector/DetCRD/compact/CRD_common_v01/materials.xml, Detector/DetCRD/compact/CRD_o1_v01/CRD_Dimensions_v01_01.xml, Detector/DetCRD/compact/CRD_o1_v01/CRD_o1_v01.xml, Detector/DetCRD/compact/CRD_o1_v02/CRD_Dimensions_v01_02.xml, Detector/DetCRD/compact/CRD_o1_v02/CRD_o1_v02.xml, Detector/DetDriftChamber/compact/det.xml, Detector/DetDriftChamber/compact/materials.xml, Detector/DetDriftChamber/src/driftchamber/DriftChamber.cpp, Detector/DetSegmentation/include/DetSegmentation/GridDriftChamber.h, Detector/DetSegmentation/src/GridDriftChamber.cpp, Detector/DetSegmentation/src/plugins/SegmentationFactories.cpp, Service/GearSvc/src/GearSvc.cpp
Change the dual drift chamber to a single drift chamber, where
1. inner radius:800mm
2. outer radius:1720mm
The radii of the inner and outer walls respectively extend outward.
Due to the modification of the inner and outer radius of the drift chamber, the parameters of the silicon detector should also be corrected accordingly. Since I am not clear, I added the parameters of the single drift chamber in the `Detector/DetCRD/compact/CRD_o1_v01/CRD_Dimensions_v01_01.xml` and `Detector/DetCRD/compact/CRD_o1_v02/CRD_Dimensions_v01_02.xml` , and the parameters of the dual drift chamber were not deleted before.
=> Change to single drift chamber and modify the percentage of gas elements

Detector/DetCRD/compact/CRD_common_v01/DC_Simple_v01_01.xml, Detector/DetCRD/compact/CRD_common_v01/Ecal_Crystal_Barrel_v01_01.xml, Detector/DetCRD/compact/CRD_o1_v01/CRD_Dimensions_v01_01.xml, Detector/DetCRD/compact/CRD_o1_v01/CRD_o1_v01-onlyTracker.xml, Detector/DetCRD/compact/CRD_o1_v01/CRD_o1_v01.xml, Detector/DetCRD/compact/CRD_o1_v02/CRD_Dimensions_v01_02.xml, Detector/DetCRD/compact/CRD_o1_v02/CRD_o1_v02-onlyTracker.xml, Detector/DetCRD/compact/README.md, Detector/DetCRD/scripts/CRD_o1_v01-SimRec.py, Detector/DetCRD/scripts/CRD_o1_v02-SimRec.py, Reconstruction/Tracking/src/Clupatra/ClupatraAlg.cpp, Reconstruction/Tracking/src/Clupatra/clupatra_new.cpp
* geometry update
* change length of DC to 2980mm 
* 4 layers SIT and one supper layer SET (one pixel or one double-side strip) 
* CRD_o1_v01: pixel for both SIT and SET
* CRD_o1_v02: pixel for SIT and strip for SET
* dispaly
* change some colors
* option
* update job option to match SIT/SET modification
* add tracker only geometry option file for tracking study
* note:
* calorimeters commented out, since overlap exists while changing inner radius of Ecal from 1800mm to 1900mm, will fix in future PR
* Clupatra for DC commented out, if want to open it, the branch [fucd/CEPCSW/surface-patch](https://github.com/fucd/CEPCSW/tree/surface-patch) is needed extraly. Because current DC hits is not always at the center of cells. This issue will be fixed through merge the `surface-patch` or update …
=> Tracker: update dimensions for silicon tracker of CRD_o1_v01 and CRD_o1_v02

.gitignore, Analysis/TrackInspect/CMakeLists.txt, Detector/GeomSvc/src/GeomSvc.cpp, Detector/GeomSvc/src/GeomSvc.h, Reconstruction/RecGenfitAlg/CMakeLists.txt, Reconstruction/Tracking/CMakeLists.txt, Service/GearSvc/src/GearSvc.h, Simulation/DetSimAna/CMakeLists.txt, Simulation/DetSimCore/CMakeLists.txt, Utilities/KalDet/CMakeLists.txt
Some small fixes specific to the compilation with clang12:
* Adds some missing linking targets to avoid genconf error
* Fixes an error with string conversion for sprintf (Probably framework logging could be used here, I'll take a look at that)
* Remove some forward declarations of DD4hep::DetElement since the header where it is declared is included before
Also:
* git-ignore spack files and directories ( useful for `spack dev-build` )
=> Fixes for compilation with clang12

CMakeLists.txt
This makes it easier to build cepcsw on the command line - until now I always had to set the cmake_modules_path by hand.
=> Set pandorapfa cmake_modules_path in cmake

Detector/DetCRD/scripts/CRD-Sim.py, Detector/DetCRD/scripts/CRD_o1_v01-SimRec.py, Detector/DetCRD/scripts/CRD_o1_v02-SimRec.py, Simulation/DetSimGeom/src/AnExampleDetElemTool.cpp, Simulation/DetSimGeom/src/AnExampleDetElemTool.h, Simulation/DetSimSD/CMakeLists.txt, Simulation/DetSimSD/src/GenericTrackerSensDetTool.cpp, Simulation/DetSimSD/src/GenericTrackerSensDetTool.h, Simulation/DetSimSD/src/GenericTrackerSensitiveDetector.cpp, Simulation/DetSimSD/src/GenericTrackerSensitiveDetector.h
In new DD4hep version, Geant4TrackerSD has been removed, to add GenericTrackerSD to avoid crash.
* GenericTrackerSensitiveDetector
* GeneticTrackerSensTool
* fix error missing DedxSimTool in job script
=> SIM：add GenericTrackerSD

Reconstruction/SiliconTracking/src/SiliconTrackingAlg.cpp, Reconstruction/SiliconTracking/src/TrackSubsetAlg.cpp, Reconstruction/Tracking/include/Tracking/TrackingHelper.h, Reconstruction/Tracking/src/Clupatra/clupatra_new.cpp, Reconstruction/Tracking/src/FullLDCTracking/FullLDCTrackingAlg.cpp, Reconstruction/Tracking/src/TruthTracker/TruthTrackerAlg.cpp, Service/TrackSystemSvc/include/TrackSystemSvc/MarlinTrkUtils.h, Service/TrackSystemSvc/src/LCIOTrackPropagators.cc, Service/TrackSystemSvc/src/MarlinKalTestTrack.cc, Service/TrackSystemSvc/src/MarlinTrkUtils.cc, Utilities/KiTrack/src/Tools/Fitter.cc
This should fix #217 .
Hi @fucd @ihepzhangyao , could you have a look at my update? In the future version of EDM4hep, the size of covMatrix is changed from 15 to 21. Please check your reconstruction algorithms. Thank you in advance. 
Tao
=> Use decltype to avoid the hardcode size for covMatrix. 

Detector/DetCRD/compact/CRD_common_v01/Beampipe_v01_01.xml, Detector/DetCRD/compact/CRD_common_v01/Beampipe_v01_02.xml, Detector/DetCRD/src/Other/CRDBeamPipe_v01_geo.cpp, Detector/DetCRD/src/Other/OtherDetectorHelpers.h
* Add RunWay type for new design
* [Detector/DetCRD/compact/CRD_common_v01/Beampipe_v01_02.xml]
* At the same time, also update
* remove the prefix DD4hep_ in detector type
* open the section which is closed because DD4hep did not support Scale in previous version
* change hardcode Vis attribution to optional in xml
=> GEOM: new type and option for new beampipe design

Generator/CMakeLists.txt, Generator/src/GtBeamBackgroundTool.cpp, Generator/src/GtBeamBackgroundTool.h, Generator/src/GuineaPigPairsFileParser.cpp, Generator/src/GuineaPigPairsFileParser.h, run.sh
Usage:
```python
beambackground = GtBeamBackgroundTool("GtBeamBackgroundTool")
beambackground.InputFileMap = {'pairs': '/cefs/higgs/xuwei/cepc_bkg/MDI/Data/lattice_v1/Generator/Beamstrahlung/HTDR_20220327_0945/GuineaPig/GP_1/pairsB.dat'}
beambackground.InputFormatMap = {'pairs': 'GuineaPigPairsFileParser'}
```
Users need to specify the parser of the format.
=> [WIP] Support GuineaPig Paris output in CEPCSW

Detector/DetCRD/compact/CRD_common_v01/Ecal_Crystal_Barrel_v01_01.xml, Detector/DetCRD/compact/CRD_o1_v02/CRD_Dimensions_v01_02.xml, Detector/DetCRD/compact/CRD_o1_v02/CRD_o1_v02-onlyEcalB.xml, Detector/DetCRD/src/Calorimeter/CRDEcal_v01.cpp
Update the crystal ECAL barrel geometry: 
- Extract some parameters from src file to config file. (Symmetry number is only validated for nsymm=8.)
- Change ECAL size: half z from 3350mm to 3300mm to avoid gaps between crystal bars (for Nblock=11).
=> Update ECAL Barrel geometry

Simulation/DetSimCore/src/DetSimSvc.cpp
At end of the event, the event is not released.
=> WIP: according to Chengdong's suggestion, fix the memory leakage in simulation framework

Detector/DetCEPCv4/compact/CepCBeamPipe_v01_01.xml
This problem has been correct in CRD, but not in CepC_v4. This commit will update.
=> GEOM: open shape unsupported in old DD4hep

Detector/DetCEPCv4/compact/CepCBeamPipe_v01_01.xml, Detector/DetCEPCv4/compact/SEcal05_siw_ECRing_02.xml, Detector/DetCEPCv4/compact/ftd_cepc_02.xml, Detector/DetCEPCv4/compact/materials.xml, Detector/DetCEPCv4/compact/top_defs.xml, Detector/DetCEPCv4/compact/vxd07_01.xml, Detector/DetCRD/compact/CRD_common_v01/Beampipe_v01_01.xml, Detector/DetCRD/compact/CRD_common_v01/Beampipe_v01_02.xml, Detector/DetCRD/compact/CRD_common_v01/materials.xml, Detector/DetCRD/compact/CRD_o1_v01/CRD_Dimensions_v01_01.xml, Detector/DetCRD/compact/CRD_o1_v02/CRD_Dimensions_v01_02.xml, Detector/DetCRD/compact/CRD_o1_v03/CRD_Dimensions_v01_03.xml, Detector/DetCRD/compact/CRD_o1_v04/CRD_Dimensions_v01_04.xml, Detector/DetCRD/src/Other/CRDBeamPipe_v01_geo.cpp
As preliminary, the CDR design of MDI lying in range of QD0 and QF1 is implemented.
At the same time, some dimensions of other sub-detectors are modified to avoid overlap.
=> GEOM: add pipe and magnet in range of QD0 and QF1

Detector/DetCEPCv4/compact/CepCBeamPipe_v01_01.xml, Detector/DetCRD/compact/CRD_common_v01/Beampipe_v01_01.xml, Detector/DetCRD/compact/CRD_common_v01/Beampipe_v01_02.xml
It is a mistake BeamPipe_QF1_zmax has a value equal to BeamPipe_QF1_zmin in PR#238. Here fix it.
=> WIP: correct wrong parameter of QF1

Analysis/DumpEvent/src/DumpTrackAlg.cpp, Reconstruction/PFA/Pandora/GaudiPandora/src/TrackCreator.cpp, Reconstruction/PFA/Pandora/MatrixPandora/src/TrackCreator.cpp, Reconstruction/SiliconTracking/src/ForwardTrackingAlg.cpp, Reconstruction/SiliconTracking/src/SiliconTrackingAlg.cpp, Reconstruction/Tracking/src/FullLDCTracking/FullLDCTrackingAlg.cpp, Service/TrackSystemSvc/src/MarlinTrkUtils.cc
Renamed for more consistency in key4hep/EDM4hep#188. This PR also introduces the minimal preprocessor things that are necessary to make things work if `EDM4hepVersion.h` is not yet available. This is necessary to make the transition a bit smoother.
=> Change capitalization of track subdetectorHitNumbers vector member

Reconstruction/PFA/Pandora/GaudiPandora/src/MCParticleCreator.cpp, Reconstruction/PFA/Pandora/GaudiPandora/src/PandoraPFAlg.cpp, Reconstruction/PFA/Pandora/GaudiPandora/src/TrackCreator.cpp, Reconstruction/PFA/Pandora/MatrixPandora/src/MCParticleCreator.cpp, Reconstruction/PFA/Pandora/MatrixPandora/src/PandoraMatrixAlg.cpp, Reconstruction/PFA/Pandora/MatrixPandora/src/TrackCreator.cpp
After https://github.com/AIDASoft/podio/pull/493, `id()` returns a `podio::ObjectID` which breaks in a few places. I have made the changes so that compiling works by using the `index` member variable but I'm not sure if everything keeps working, it would be great if someone can have a look.
=> Fix ObjectID issues

cmake/CEPCSWConfig.cmake
I think it isn't being used in any place and then we can remove it from the key4hep stack since now conversions in both ways are provided in https://github.com/key4hep/k4EDM4hep2LcioConv
=> Remove k4LCIOReader

Analysis/TrackInspect/src/TrackInspectAlg.cpp, Reconstruction/PFA/Arbor/src/ArborToolLCIO.cc, Reconstruction/Tracking/src/Clupatra/clupatra_new.cpp, Reconstruction/Tracking/src/Clupatra/clupatra_new.h, Service/TrackSystemSvc/src/MarlinKalTestTrack.cc, Service/TrackSystemSvc/src/MarlinTrkUtils.cc, Utilities/DataHelper/src/TrackExtended.cc
The public object constructor from an `Obj*` is removed with AIDASoft/podio#514 and instead replaced with the `makeEmpty` factory method that has the same result. This PR introduces the necessary changes in a backwards compatible manner, so that things should keep working after the podio PR has been merged. 
If a sort of "clean cut" is desired I can also remove the pre-processor checks and instead bump the required podio version in the CMake configuration to keep things working. In that case we would have to wait until AIDASoft/podio#514 is merged and there is a new podio tag after that.
=> Move to makeEmpty factory methods for initializing empty edm4hep objects

Analysis/DumpEvent/src/DumpMCParticleAlg.cpp, Digitisers/SimpleDigi/src/TPCDigiAlg.cpp, Reconstruction/RecGenfitAlg/src/GenfitTrack.cpp, Reconstruction/RecGenfitAlg/src/GenfitTrack.h, Reconstruction/RecGenfitAlg/src/RecGenfitAlgDC.cpp, Reconstruction/Tracking/src/TruthTracker/TruthTrackerAlg.cpp, Simulation/DetSimCore/src/G4PrimaryCnvTool.cpp
Remove the explicit mentionings of `edm4hep::Vector3f` for cases where an `auto` does the trick. This makes it easier to switch representations while being backwards compatible. This is necessary for key4hep/EDM4hep#237
=> Remove explicit mentionings of MCParticle momentum type

Detector/DetDriftChamber/compact/det.xml, Examples/options/tut_detsim_SDT_Heed.py, Simulation/DetSimAna/src/Edm4hepWriterAnaElemTool.cpp, Simulation/DetSimAna/src/Edm4hepWriterAnaElemTool.h, Simulation/DetSimDedx/CMakeLists.txt, Simulation/DetSimDedx/src/TrackHeedSimTool.cpp, Simulation/DetSimDedx/src/TrackHeedSimTool.h, Simulation/DetSimInterface/include/DetSimInterface/IDedxSimTool.h, Simulation/DetSimSD/src/DriftChamberSensDetTool.cpp, Simulation/DetSimSD/src/DriftChamberSensitiveDetector.cpp, cmake/FindOnnxRuntime.cmake, run.sh
=> add TrackHeedSimTool for DC cell simulation

CMakeLists.txt
I was able to build with C++20 after this. There are many warnings, if anyone is interested in fixing those most of them looked easy...
=> Allow building with C++20

Detector/DetCRD/scripts/CRD-Sim.py, Detector/DetCRD/scripts/CRD_VXD_MOST2-sim.py, Detector/DetCRD/scripts/CRD_o1_v01-SimRec.py, Detector/DetCRD/scripts/CRD_o1_v02-SimRec.py, Detector/DetCRD/scripts/Standalone-Sim-RotCrystal.py, Digitisers/SimpleDigi/src/PlanarDigiAlg.cpp, Digitisers/SimpleDigi/src/PlanarDigiAlg.h
* import Riccardo's parametrized model
* example to use
* default not use, and in python example, commented by #, if want to use, remove # 
* update python example to LCG 102+
=> Digi: import parameterized model for silicon spatial resolution

Generator/CMakeLists.txt, Generator/src/HepevtRdr.cpp, Generator/src/HepevtRdr.h, Generator/src/LCAscHepRdr.cc
Example:
```python
hepevtrdr = HepevtRdr("HepevtRdr")
hepevtrdr.Input = "tao_test.txt"
hepevtrdr.Format = "HEPEvt" # or 'hepevt'
genprinter = GenPrinter("GenPrinter")
genprinter.OutputLevel = DEBUG
genalg = GenAlgo("GenAlgo")
genalg.GenTools = ["HepevtRdr", "GenPrinter"]
```
=> migrate the HepEvt reader.

.github/workflows/main.yml, build-k4.sh
Due to the API change in EDM4hep, the CEPCSW is not built with the latest Key4hep stack. Some dependencies are not built.
=> Handling the CI related to KEYHEP_STACK
